### ISSUE TITLE
joystick code errors

### ISSUE THREAD

**Issue by jamessanford** [jamessanford/kegs#3]
Looks like the joystick code may have a bug (it needs to be rewritten anyhow, but right now it may crash!)

I suspect it's related to multitouch actions during joystick movement.

Three reports of this in the android developer console, with different phones and versions of android:

java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:2148)
at com.froop.app.kegs.TouchSpecialZone.click(TouchSpecialZone.java:20)
at com.froop.app.kegs.TouchJoystick.onTouchEvent(TouchJoystick.java:142)
com.froop.app.kegs.KegsMain$11.onTouch(KegsMain.java:550)
at android.view.View.dispatchTouchEvent(View.java:8107)

**Comment by jamessanford** [comment]
This continues to be a problem, with 19 reported crashes affecting 15 users on Google Play.
